DEFAULT_SLEEP = 10
HEADLESS = False
PROXY = ''

EXTENTION_IDENTIFIER = 'aflkmfhebedbjioipglgcbcmnbpgliof'
EXTENTION_VERSION = '0.10.92_0'
EXTENTION_PATH = f''
EXTENTION_PASSWORD = ''

PHOENIX_URL = 'https://app.phoenix.trade/market/4DoNfFBfF7UokCC2FQzriy7yHK6DY6NVdYpuekQ5pRgg'

SLOW_MO = None
# SLOW_MO = 600
ATTEMPTS_NUMBER_RESTORE = 10

SOL_TO_SELL = 0.001
