DEFAULT_SLEEP = 10
HEADLESS = False
PROXY = ''

EXTENTION_IDENTIFIER = 'aflkmfhebedbjioipglgcbcmnbpgliof'
EXTENTION_VERSION = '0.10.80_0'
EXTENTION_PATH = ''
EXTENTION_PASSWORD = '1234567890'

PHOENIX_URL = 'https://app.phoenix.trade/market/3J9LfemPBLowAJgpG3YdYPB9n6pUk7HEjwgS6Y5ToSFg'

SLOW_MO = None
# SLOW_MO = 600
ATTEMPTS_NUMBER_RESTORE = 10

SOL_TO_SELL = 0.01
