"""add column completed2

Revision ID: acd764b4ed29
Revises: aee0c3cd9380
Create Date: 2024-03-12 19:02:49.696275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acd764b4ed29'
down_revision: Union[str, None] = 'aee0c3cd9380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('completed2', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'completed2')
    # ### end Alembic commands ###
