"""add column completed3

Revision ID: 86d4460466e7
Revises: acd764b4ed29
Create Date: 2024-03-12 19:05:17.582103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d4460466e7'
down_revision: Union[str, None] = 'acd764b4ed29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('completed3', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'completed3')
    # ### end Alembic commands ###
